<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Infrastructure</AssemblyName>
    <RootNamespace>Infrastructure</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="BigEndianBitConverter.fs" />
    <Compile Include="Functional.fs" />
    <Compile Include="ReaderResult.fs" />
    <Compile Include="Ref.fs" />
    <Compile Include="Result.fs" />
    <Compile Include="BigInteger.fs" />
    <Compile Include="Security.fs" />
    <Compile Include="Endpoint.fs" />
    <Compile Include="Option.fs" />
    <Compile Include="List.fs" />
    <Compile Include="LogEvent.fs" />
    <Compile Include="Log.fs" />
    <Compile Include="ServiceBusMessage.fs" />
    <Compile Include="ServiceBus.fs" />
    <Compile Include="EventBus.fs" />
    <Compile Include="Timestamp.fs" />
    <Compile Include="Measure.fs" />
    <Compile Include="Writer.fs" />
    <Compile Include="Actor.fs" />
    <Compile Include="Http.fs" />
    <Compile Include="Disposables.fs" />
    <Compile Include="Subject.fs" />
    <Content Include="ServiceBusMessage.xml" />
    <Compile Include="Exception.fs" />
    <Compile Include="Platform.fs" />
    <Compile Include="ZFStar.fs" />
    <Compile Include="Map.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsPickler" />
    <PackageReference Include="FSharp.Control.Reactive" />
    <PackageReference Include="System.Reactive.Compatibility" />
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="FSharpx.Extras" />
    <PackageReference Include="BouncyCastle" />
  </ItemGroup>
</Project>