<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>TestsInfrastructure</AssemblyName>
    <RootNamespace>TestsInfrastructure</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Constraints.fs" />
    <Compile Include="FsCheck.fs" />
    <Compile Include="NUnit.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsUnit" />
    <PackageReference Include="FsCheck.NUnit" />
  </ItemGroup>
</Project>