<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Infrastructure.Tests</AssemblyName>
    <RootNamespace>Infrastructure.Tests</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Setup.fs" />
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="EndpointTests.fs" />
    <Compile Include="EventBus.Tests.fs" />
    <Compile Include="HttpAgentTests.fs" />
    <Compile Include="ServiceBus.Tests.fs" />
    <Compile Include="ServiceBusMessage.Tests.fs" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <Compile Include="Platform.Tests.fs" />
    <Compile Include="ZFStar.Tests.fs" />
    <ProjectReference Include="..\TestsInfrastructure\TestsInfrastructure.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsUnit" />
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="FSharp.Control.Reactive" />
    <PackageReference Include="System.Reactive.Compatibility" />
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>