<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Wallet.Tests</AssemblyName>
    <RootNamespace>Wallet.Tests</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE;MONO_LOG_LEVEL=debug</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AccountTests.fs" />
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="KeyPathParserTests.fs" />
    <Compile Include="SerializationTests.fs" />
    <Compile Include="AddressTests.fs" />
    <None Include="app.config" />
    <ProjectReference Include="..\Consensus.Tests\Consensus.Tests.fsproj" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
    <ProjectReference Include="..\Wallet\Wallet.fsproj" />
    <ProjectReference Include="..\TestsInfrastructure\TestsInfrastructure.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsUnit" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsCheck.NUnit" />
    <PackageReference Include="zen_secp256k1_linux" />
    <PackageReference Include="NBitcoin" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>