<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Blockchain</AssemblyName>
    <RootNamespace>Blockchain</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Tally_Types.fs" />
    <Compile Include="Tally.fs" />
    <Compile Include="Tally_Nomination.fs" />
    <Compile Include="Tally_Voting.fs" />
    <Compile Include="Tally_VoteParser.fs" />
    <Compile Include="BlockState.fs" />
    <Compile Include="ExtendedBlockHeader.fs" />
    <Compile Include="Serialization.fs" />
    <Compile Include="DatabaseContext.fs" />
    <Compile Include="Tally_Repository.fs" />
    <Compile Include="Environment.fs" />
    <Compile Include="TransactionRepository.fs" />
    <Compile Include="UtxoSetRepository.fs" />
    <Compile Include="ContractUtxoRepository.fs" />
    <Compile Include="ContractStateRepository.fs" />
    <Compile Include="ActiveContractSetRepository.fs" />
    <Compile Include="BlockRepository.fs" />
    <Compile Include="Tree.fs" />
    <Compile Include="EffectsWriter.fs" />
    <Compile Include="OrphanPool.fs" />
    <Compile Include="MemPool.fs" />
    <Compile Include="InitialBlockDownload.fs" />
    <Compile Include="State.fs" />
    <Compile Include="TransactionHandler.fs" />
    <Compile Include="Chain.fs" />
    <Compile Include="Tally_Handler.fs" />
    <Compile Include="ChainConnection.fs" />
    <Compile Include="BlockHandler.fs" />
    <Compile Include="BlockTemplateBuilder.fs" />
    <Compile Include="Handler.fs" />
    <Compile Include="main.fs" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
    <ProjectReference Include="..\Wallet\Wallet.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="FSharpx.Extras" />
    <PackageReference Include="FSharp.Control.Reactive" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="System.Reactive.Compatibility" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>