<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>zen-cli</AssemblyName>
    <RootNamespace>Cli</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="FsBech32, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null">
      <HintPath>..\..\packages\FsBech32\lib\net47\FsBech32.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Util.fs" />
    <Compile Include="Request.fs" />
    <Compile Include="Program.fs" />
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Api\Api.fsproj" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Argu" />
    <PackageReference Include="NBitcoin" />
  </ItemGroup>
</Project>