<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>SerializationBenchmark</AssemblyName>
    <RootNamespace>SerializationBenchmark</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Program.fs" />
    <Content Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsBech32" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="zen_secp256k1_linux" />
  </ItemGroup>
</Project>