<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Helper.Tests</AssemblyName>
    <RootNamespace>Helper.Tests</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Setup.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AddressDB\AddressDB.fsproj" />
    <ProjectReference Include="..\Api\Api.fsproj" />
    <ProjectReference Include="..\Blockchain.Tests\Blockchain.Tests.fsproj" />
    <ProjectReference Include="..\Blockchain\Blockchain.fsproj" />
    <ProjectReference Include="..\Cli\Cli.fsproj" />
    <ProjectReference Include="..\Consensus.Tests\Consensus.Tests.fsproj" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
    <ProjectReference Include="..\Network\Network.fsproj" />
    <ProjectReference Include="..\Wallet\Wallet.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="System.Reactive.Compatibility" />
    <PackageReference Include="zen_secp256k1_linux" />
    <PackageReference Include="NBitcoin" />
    <PackageReference Include="FsUnit" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>