<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Network.Tests</AssemblyName>
    <RootNamespace>Network.Tests</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="InProcMessage.Tests.fs" />
    <Compile Include="NetworkMessage.Tests.fs" />
    <Compile Include="PeerTests.fs" />
    <Compile Include="TransportHelper.fs" />
    <Compile Include="TransportTests.fs" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Network\Network.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsUnit" />
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="FSharp.Control.Reactive" />
    <PackageReference Include="System.Reactive.Compatibility" />
  </ItemGroup>
</Project>