<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Wallet</AssemblyName>
    <RootNamespace>Wallet</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Address.fs" />
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="KeyPathParser.fs" />
    <Compile Include="ExtendedKey.fs" />
    <Compile Include="Types.fs" />
    <Compile Include="Secured.fs" />
    <Compile Include="Serialization.fs" />
    <Compile Include="DataAccess.fs" />
    <Compile Include="View.fs" />
    <Compile Include="Account.fs" />
    <Compile Include="TransactionCreator.fs" />
    <Compile Include="Main.fs" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FSharp.Control.Reactive" />
    <PackageReference Include="NBitcoin" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>