<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Blockchain.Tests</AssemblyName>
    <RootNamespace>Blockchain.Tests</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Setup.fs" />
    <Compile Include="Tally.Tests\Voting Contractract.fs" />
    <Compile Include="InitialBlockDownloadTests.fs" />
    <Compile Include="SerializationTests.fs" />
    <Compile Include="ValidateBlockTests.fs" />
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="ContractMessageTests.fs" />
    <Compile Include="SimpleWalletContractTests.fs" />
    <Compile Include="MintingContractTests.fs" />
    <Compile Include="ValidateTransactionTests.fs" />
    <Compile Include="TallyChainTest.fs" />
    <Compile Include="TallyValidation.fs" />
    <ProjectReference Include="..\Api\Api.fsproj" />
    <ProjectReference Include="..\Blockchain\Blockchain.fsproj" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
    <ProjectReference Include="..\Wallet\Wallet.fsproj" />
    <ProjectReference Include="..\Consensus.Tests\Consensus.Tests.fsproj" />
    <ProjectReference Include="..\TestsInfrastructure\TestsInfrastructure.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsUnit" />
    <PackageReference Include="FsCheck.NUnit" />
    <PackageReference Include="zen_secp256k1_linux" />
    <PackageReference Include="FSharpx.Extras" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>