<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Zulib.Tests</AssemblyName>
    <RootNamespace>Zulib.Tests</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <None Include="BitcoinBlock.json" />
    <Compile Include="Helper.fs" />
    <Compile Include="AssetTests.fs" />
    <Compile Include="BitcoinTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsUnit" />
    <PackageReference Include="FsCheck.NUnit" />
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>