<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>zen-node</AssemblyName>
    <RootNamespace>Node</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Program.fs" />
    <Content Include="main.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="scheme.yaml" />
    <Content Include="test.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="zen-cli">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="zen-node">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AddressDB\AddressDB.fsproj" />
    <ProjectReference Include="..\Api\Api.fsproj" />
    <ProjectReference Include="..\Blockchain\Blockchain.fsproj" />
    <ProjectReference Include="..\Cli\Cli.fsproj" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
    <ProjectReference Include="..\Miner\Miner.fsproj" />
    <ProjectReference Include="..\Network\Network.fsproj" />
    <ProjectReference Include="..\Wallet\Wallet.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FSharp.Control.Reactive" />
    <PackageReference Include="System.Reactive.Compatibility" />
    <PackageReference Include="Argu" />
    <PackageReference Include="zen_secp256k1_linux" />
    <PackageReference Include="Zulib" />
  </ItemGroup>
</Project>