<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Network</AssemblyName>
    <RootNamespace>Network</RootNamespace>
    <OtherFlags>--warnon:1182</OtherFlags>
    <PlatformTarget>x64</PlatformTarget>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Tailcalls>false</Tailcalls>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Tailcalls>true</Tailcalls>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Types.fs" />
    <Compile Include="Serialization.fs" />
    <Compile Include="DiscoverIP.fs" />
    <Compile Include="NetworkMessage.fs" />
    <Compile Include="Transport\InProcMessage.fs" />
    <Compile Include="Transport\Peer.fs" />
    <Compile Include="Transport\Transport.fs" />
    <Content Include="Transport\InProcMessage.xml" />
    <Compile Include="AddressBook.fs" />
    <Compile Include="Connector.fs" />
    <Compile Include="TransactionPublisher.fs" />
    <Compile Include="Main.fs" />
    <Content Include="NetworkMessage.xml" />
    <ProjectReference Include="..\Consensus\Consensus.fsproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.fsproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.fsproj" />
    <ProjectReference Include="..\Messaging\Messaging.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsPickler" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="FsNetMQ" />
    <PackageReference Include="FSharp.Control.Reactive" />
    <PackageReference Include="System.Reactive.Compatibility" />
    <PackageReference Include="FSharp.Data" />
  </ItemGroup>
</Project>